// Generated by tools/build_web.py — offline cache for Solunar Sprouts 2026.09.27-1526-bbef9a.
// A new build changes VERSION, so phones download the new files, then the game offers "Update now".
const VERSION = '2026.09.27-1526-bbef9a';
const CACHE = 'solunar-app-' + VERSION;
const FONT_CACHE = 'solunar-fonts';
const ASSETS = ["./", "index.html", "app.css", "app.js", "battle.js", "data.js", "garden.js", "menu.js", "pixel.js", "race.js", "shop.js", "sprouts.js", "state.js", "ui.css", "icons/apple-touch-icon.png", "icons/icon-192.png", "icons/icon-512.png", "version.js", "manifest.webmanifest"];

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE)
    .then(cache => cache.addAll(ASSETS.map(u => new Request(u, { cache: 'reload' }))))
    .then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith('solunar-app-') && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin === self.location.origin) {
    if (req.mode === 'navigate') {
      event.respondWith(caches.match('index.html').then(hit => hit || fetch(req)));
      return;
    }
    event.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req)));
    return;
  }
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    event.respondWith(caches.open(FONT_CACHE).then(async cache => {
      const hit = await cache.match(req);
      const net = fetch(req).then(res => { if (res.ok || res.type === 'opaque') cache.put(req, res.clone()); return res; }).catch(() => hit);
      return hit || net;
    }));
  }
});
